version: '3.7'

services:
  web:
    build: .
    container_name: iis_shelter
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.template
    environment:
      - DB_HOST=db
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    networks:
      - iis_shelter_net

  db:
    image: mysql:5.7
    container_name: iis_shelter_db
    env_file:
      - .env.template
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iis
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - iis_shelter_net

networks:
    iis_shelter_net:
        name: iis_shelter_net
        driver: bridge

volumes:
    db_data: