"""password is bytes now

Revision ID: 95ae11205190
Revises: 78888ec2f0f9
Create Date: 2024-11-01 01:07:41.392969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '95ae11205190'
down_revision: Union[str, None] = '78888ec2f0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animals', 'photo',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.LargeBinary(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.LargeBinary(length=1024),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('animals', 'photo',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
